# Generated by Django 5.1.3 on 2025-07-01 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logo/", verbose_name="Логотип"
                    ),
                ),
                (
                    "commander",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commander",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Командир",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="team_players",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Игроки команды",
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
            },
        ),
        migrations.CreateModel(
            name="TeamRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("accepted", "Принято"),
                            ("rejected", "Отклонено"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.team",
                        verbose_name="Команда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка в команду",
                "verbose_name_plural": "Заявки в команды",
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания турнира"
                    ),
                ),
                (
                    "registration_start_date",
                    models.DateTimeField(
                        editable=False, verbose_name="Дата начала регистрации"
                    ),
                ),
                (
                    "registration_end_date",
                    models.DateTimeField(
                        editable=False, verbose_name="Дата окончания регистрации"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        editable=False, verbose_name="Дата начала турнира"
                    ),
                ),
                (
                    "team_size",
                    models.CharField(
                        choices=[
                            ("1", "solo"),
                            ("2", "duo"),
                            ("3", "trio"),
                            ("4", "squad"),
                            ("5", "full"),
                        ],
                        max_length=1,
                        verbose_name="Размер команды",
                    ),
                ),
                (
                    "maximum_number_of_teams",
                    models.PositiveIntegerField(
                        verbose_name="Максимальное количество команд"
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Цена взноса")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Завершен"),
                            ("incomplete", "Не завершен"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Модератор",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.game",
                        verbose_name="Игра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Турнир",
                "verbose_name_plural": "Турниры",
            },
        ),
        migrations.CreateModel(
            name="TeamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(verbose_name="Очки команды")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="tournaments.team",
                        verbose_name="Команда",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат команды",
                "verbose_name_plural": "Результаты команд",
            },
        ),
        migrations.CreateModel(
            name="TeamComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="team_composition_players",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Игроки состава",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.team",
                        verbose_name="Команда",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состав команды",
                "verbose_name_plural": "Составы команд",
            },
        ),
        migrations.CreateModel(
            name="TournamentRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата подачи заявки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending payment", "ожидание оплаты"),
                            ("payment confirmed", "оплата подтверждена"),
                            ("payment_failed", "оплата не прошла"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "team_composition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.team",
                        verbose_name="Состав команды",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на турнир",
                "verbose_name_plural": "Заявки на турниры",
            },
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_date__gte", models.F("registration_start_date"))
                ),
                name="start_date_after_or_equal_to_registration_start_date",
            ),
        ),
    ]
